/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unad.poo.views;

import com.unad.poo.ProgramaJavaApplication;
import com.unad.poo.SpringContext;
import com.unad.poo.models.Ciudad;
import com.unad.poo.models.Rol;
import com.unad.poo.models.Departamento;
import com.unad.poo.models.Empleado;
import com.unad.poo.models.Rol;
import com.unad.poo.repository.CiudadRepository;
import com.unad.poo.repository.DepartamentoRepository;
import com.unad.poo.repository.EmpleadoRepository;
import com.unad.poo.repository.RolRepository;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import java.util.Optional;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author FERNi
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    DefaultTableModel tabla = new DefaultTableModel();
    ArrayList<Departamento> datosDep = new ArrayList<>();
    ArrayList<Ciudad> datosCiudad = new ArrayList<>();
    ArrayList<Empleado> datosEmp = new ArrayList<>();
    ArrayList<Rol> datosRol = new ArrayList<>();

    CiudadRepository ciudadCrud;
    EmpleadoRepository empleadoCrud;
    DepartamentoRepository depCrud;
    RolRepository rolCrud;
    Empleado emp = new Empleado();
    Rol rol = new Rol();
    Ciudad ciudad = new Ciudad();
    Departamento dep = new Departamento();

    EmpleadoFrame empControl = new EmpleadoFrame();

    public AdminFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(920, 670);
        this.setResizable(false);
        String[] args = {};
        ProgramaJavaApplication.runSpringServer(args);

        empleadoCrud = SpringContext.getBean(EmpleadoRepository.class);
        ciudadCrud = SpringContext.getBean(CiudadRepository.class);
        depCrud = SpringContext.getBean(DepartamentoRepository.class);
        rolCrud = SpringContext.getBean(RolRepository.class);

        llenarTabla();
        mostrarRoles(RolCmb);
        bloquearCamposReg();
        empControl.mostrarDepartamentos(depCmb);
        empControl.mostrarCiudad(depCmb, cityCmb);
        empControl.mostrarDepartamentos(depRCmb);
        empControl.mostrarCiudad(depRCmb, cityRCmb);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGrupAdmin = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        userCrud = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        lastTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        dataDate = new com.toedter.calendar.JDateChooser();
        depCmb = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cityCmb = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        RolCmb = new javax.swing.JComboBox<>();
        usernameTxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        IdentiCmb = new javax.swing.JComboBox<>();
        regRb = new javax.swing.JRadioButton();
        searchRb = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        notificaTxt = new javax.swing.JLabel();
        cityCrud = new javax.swing.JPanel();
        depRCmb = new javax.swing.JComboBox<>();
        cityRCmb = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setText("Id Empleado");

        idTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        idTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idTxtFocusLost(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTxtKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        nameTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTxtKeyTyped(evt);
            }
        });

        lastTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        lastTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastTxtKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel4.setText("Departamento:");

        dateTxt.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        dateTxt.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");

        telTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        telTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telTxtKeyTyped(evt);
            }
        });

        regButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        regButton.setText("Registrar");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        updateButton.setText("Actualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        depCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depCmbItemStateChanged(evt);
            }
        });
        depCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depCmbActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel27.setText("Ciudad:");

        jLabel29.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel29.setText("Correo:");

        correoTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel28.setText("Rol:");

        RolCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RolCmbActionPerformed(evt);
            }
        });

        usernameTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel30.setText("Username:");

        jLabel31.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel31.setText("Password:");

        passwordTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Celular", "Nacimiento", "Correo", "Username", "Contraseña", "Identificador", "Ciudad", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dataTable);

        jLabel32.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel32.setText("Identificador:");

        IdentiCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        radioGrupAdmin.add(regRb);
        regRb.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        regRb.setText("Registrar");
        regRb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                regRbStateChanged(evt);
            }
        });
        regRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRbActionPerformed(evt);
            }
        });

        radioGrupAdmin.add(searchRb);
        searchRb.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        searchRb.setText("Consultar");
        searchRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRbActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        notificaTxt.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        notificaTxt.setText("\"\"");

        javax.swing.GroupLayout userCrudLayout = new javax.swing.GroupLayout(userCrud);
        userCrud.setLayout(userCrudLayout);
        userCrudLayout.setHorizontalGroup(
            userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(dateTxt))
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(47, 47, 47)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdentiCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataDate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCrudLayout.createSequentialGroup()
                                .addComponent(notificaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)))
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userCrudLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userCrudLayout.createSequentialGroup()
                                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel29))
                                        .addGap(18, 18, 18)
                                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(correoTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                            .addComponent(lastTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userCrudLayout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RolCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(userCrudLayout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regRb)
                                    .addComponent(searchRb)))
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addComponent(regButton)
                                .addGap(36, 36, 36)
                                .addComponent(updateButton)
                                .addGap(41, 41, 41)
                                .addComponent(deleteButton)))
                        .addGap(17, 17, 17))
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        userCrudLayout.setVerticalGroup(
            userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCrudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(userCrudLayout.createSequentialGroup()
                                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(userCrudLayout.createSequentialGroup()
                                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(lastTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dateTxt)
                                                    .addComponent(dataDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel29)
                                                .addComponent(correoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(depCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(RolCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30))
                            .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(IdentiCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(regButton)
                            .addComponent(updateButton)
                            .addComponent(deleteButton)))
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(regRb)
                        .addGap(18, 18, 18)
                        .addComponent(searchRb)))
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(cancelButton))
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notificaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Empleados", userCrud);

        depRCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        depRCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depRCmbItemStateChanged(evt);
            }
        });

        cityRCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel22.setText("Departamento:");

        jLabel23.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel23.setText("Ciudad:");

        jLabel24.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel24.setText("Reportes");

        jButton1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jButton1.setText("Usuarios por Ciudad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jButton2.setText("Envios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jButton3.setText("Empleados Registrados");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jButton4.setText("Clientes Registrados");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cityCrudLayout = new javax.swing.GroupLayout(cityCrud);
        cityCrud.setLayout(cityCrudLayout);
        cityCrudLayout.setHorizontalGroup(
            cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityCrudLayout.createSequentialGroup()
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cityCrudLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cityCrudLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(38, 38, 38)
                                .addComponent(cityRCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cityCrudLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(39, 39, 39)
                                .addComponent(depRCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(cityCrudLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel24)))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        cityCrudLayout.setVerticalGroup(
            cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(depRCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityRCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", cityCrud);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        registrarOActualizarEmpleado();
        // TODO add your handling code here:
    }//GEN-LAST:event_regButtonActionPerformed

    private void depCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depCmbItemStateChanged
        // TODO add your handling code here:
        empControl.changeStateDep(evt, depCmb, cityCmb);
    }//GEN-LAST:event_depCmbItemStateChanged

    private void depRCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depRCmbItemStateChanged
        // TODO add your handling code here:
        empControl.changeStateDep(evt, depRCmb, cityRCmb);
    }//GEN-LAST:event_depRCmbItemStateChanged

    private void depCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depCmbActionPerformed

    private void regRbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_regRbStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_regRbStateChanged

    private void regRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRbActionPerformed
        // TODO add your handling code here:
        funcionRadioButtons();
    }//GEN-LAST:event_regRbActionPerformed

    private void searchRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRbActionPerformed
        // TODO add your handling code here:
        funcionRadioButtons();
    }//GEN-LAST:event_searchRbActionPerformed

    private void idTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtFocusLost

    private void idTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusGained
        // TODO add your handling code here:
        notificaTxt.setText("");
    }//GEN-LAST:event_idTxtFocusGained

    private void RolCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RolCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RolCmbActionPerformed

    private void nameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyTyped
        // TODO add your handling code here:
        empControl.verificaNumero(evt);
    }//GEN-LAST:event_nameTxtKeyTyped

    private void idTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyTyped
        // TODO add your handling code here:
        empControl.verificaLetra(evt);
    }//GEN-LAST:event_idTxtKeyTyped

    private void lastTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastTxtKeyTyped
        // TODO add your handling code here:
        empControl.verificaNumero(evt);
    }//GEN-LAST:event_lastTxtKeyTyped

    private void telTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telTxtKeyTyped
        // TODO add your handling code here:
        empControl.verificaLetra(evt);
    }//GEN-LAST:event_telTxtKeyTyped

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        registrarOActualizarEmpleado();
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        limpiarReg();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteEmpleado(evt);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void llenarTabla() {
        Object[] empleadoM = new Object[11];
        tabla = (DefaultTableModel) dataTable.getModel();
        try {
            datosEmp = (ArrayList<Empleado>) empleadoCrud.findAll();
            for (int i = 0; i < datosEmp.size(); i++) {
                empleadoM[0] = datosEmp.get(i).getId();
                empleadoM[1] = datosEmp.get(i).getNombre();
                empleadoM[2] = datosEmp.get(i).getApellido();
                empleadoM[3] = datosEmp.get(i).getCelular();
                empleadoM[4] = datosEmp.get(i).getFecha_n();
                empleadoM[5] = datosEmp.get(i).getCorreo();
                empleadoM[6] = datosEmp.get(i).getUsername();
                empleadoM[7] = datosEmp.get(i).getContraseña();
                empleadoM[8] = datosEmp.get(i).getIdentificador();
                empleadoM[9] = datosEmp.get(i).getCiudad().getNombre();
                empleadoM[10] = datosEmp.get(i).getRol().getNombre();
                tabla.addRow(empleadoM);
            }
        } catch (Exception e) {
        }
    }

    private void mostrarRoles(JComboBox rolCmb) {
        datosRol = (ArrayList<Rol>) rolCrud.findAll();
        Iterator<Rol> rolIterator = datosRol.iterator();
        while (rolIterator.hasNext()) {
            rolCmb.addItem(rolIterator.next().getNombre());
        }
    }

    private void funcionRadioButtons() {
        //isPresent retorna null
        try {
            Optional<Empleado> buscaEmpleado = empleadoCrud.findById(Long.parseLong(idTxt.getText()));
            if (buscaEmpleado.isPresent()) {
                if (regRb.isSelected()) {
                    notificaTxt.setText("El Empleado con id: " + idTxt.getText() + "\n ya existe");
                    radioGrupAdmin.clearSelection();
                }

                if (searchRb.isSelected()) {
                    regRb.setEnabled(false);
                    habilitarCamposReg();
                    idTxt.setEnabled(false);
                    nameTxt.setText(buscaEmpleado.get().getNombre());
                    lastTxt.setText(buscaEmpleado.get().getApellido());
                    dataDate.setDate(buscaEmpleado.get().getFecha_n());
                    depCmb.setSelectedItem(buscaEmpleado.get().getCiudad().getIdDepartamento().getNombre());
                    cityCmb.setSelectedItem(buscaEmpleado.get().getCiudad().getNombre());
                    telTxt.setText(buscaEmpleado.get().getCelular());
                    correoTxt.setText(buscaEmpleado.get().getCorreo());
                    usernameTxt.setText(buscaEmpleado.get().getUsername());
                    passwordTxt.setText(buscaEmpleado.get().getContraseña());
                    RolCmb.setSelectedItem(buscaEmpleado.get().getRol().getNombre());
                    IdentiCmb.setSelectedItem(buscaEmpleado.get().getIdentificador());
                    updateButton.setEnabled(true);
                    deleteButton.setEnabled(true);
                    cancelButton.setEnabled(true);
                }
            } else {
                if (regRb.isSelected()) {
                    habilitarCamposReg();
                    idTxt.setEnabled(false);
                    regButton.setEnabled(true);
                    searchRb.setEnabled(false);
                    notificaTxt.setText("id Disponible");
                    cancelButton.setEnabled(true);
                }
                if (searchRb.isSelected()) {
                    notificaTxt.setText("El Empleado con id " + idTxt.getText() + "\n no existe");
                    radioGrupAdmin.clearSelection();
                }
            }
        } catch (Exception e) {
            notificaTxt.setText("Ha ocurrido un error inesperado");
            radioGrupAdmin.clearSelection();
        }

    }

    private void habilitarCamposReg() {
        nameTxt.setEnabled(true);
        lastTxt.setEnabled(true);
        dataDate.setEnabled(true);
        depCmb.setEnabled(true);
        cityCmb.setEnabled(true);
        correoTxt.setEnabled(true);
        usernameTxt.setEnabled(true);
        passwordTxt.setEnabled(true);
        RolCmb.setEnabled(true);
        IdentiCmb.setEnabled(true);
        telTxt.setEnabled(true);
    }

    private void bloquearCamposReg() {
        nameTxt.setEnabled(false);
        lastTxt.setEnabled(false);
        dataDate.setEnabled(false);
        depCmb.setEnabled(false);
        cityCmb.setEnabled(false);
        correoTxt.setEnabled(false);
        usernameTxt.setEnabled(false);
        passwordTxt.setEnabled(false);
        RolCmb.setEnabled(false);
        IdentiCmb.setEnabled(false);
        telTxt.setEnabled(false);
        regButton.setEnabled(false);
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        cancelButton.setEnabled(false);
    }

    private void limpiarReg() {
        nameTxt.setText("");
        lastTxt.setText("");
        dataDate.setCalendar(null);
        depCmb.setSelectedIndex(1);
        correoTxt.setText("");
        passwordTxt.setText("");
        usernameTxt.setText("");
        RolCmb.setSelectedIndex(1);
        IdentiCmb.setSelectedIndex(1);
        telTxt.setText("");
        radioGrupAdmin.clearSelection();
        regRb.setEnabled(true);
        searchRb.setEnabled(true);
        notificaTxt.setText("");
        idTxt.setEnabled(true);
        bloquearCamposReg();
    }

    private void registrarOActualizarEmpleado() {

        emp = setterEmpleado(cityCmb, RolCmb);

        if (validarCamposNullos() == false) {
            JOptionPane.showMessageDialog(this, "No se aceptan campos Nullos",
                    "Empleado no guardado", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                empleadoCrud.save(emp);
                notificaTxt.setText("Empleado guardado exitosamente");
                limpiarReg();
                idTxt.setEnabled(true);
                tabla.setRowCount(0);
                llenarTabla();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Campos sin Llenar o "
                        + "llenados incorrectamente", "Cliente no guardado",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private Rol obtenerIdRol(String rolName) {
        Rol objectRol = rolCrud.findByNombre(rolName);
        return objectRol;
    }

    private Empleado setterEmpleado(JComboBox cityId, JComboBox rolId) {
        emp.setId(Long.parseLong(idTxt.getText()));
        emp.setNombre(nameTxt.getText());
        emp.setApellido(lastTxt.getText());
        emp.setFecha_n(dataDate.getDate());
        emp.setUsername(usernameTxt.getText());
        emp.setContraseña(passwordTxt.getText());
        emp.setRol(obtenerIdRol(rolId.getSelectedItem().toString()));
        String charIdenti = IdentiCmb.getSelectedItem().toString();
        emp.setIdentificador(charIdenti.charAt(0));
        emp.setCiudad(empControl.obtenerIdCiudad(cityId.getSelectedItem().toString()));
        emp.setCorreo(correoTxt.getText());
        emp.setCelular(telTxt.getText());

        return emp;
    }

    private boolean validarCamposNullos() {
        if (nameTxt.getText().isEmpty() || lastTxt.getText().isEmpty()
                || usernameTxt.getText().isEmpty() || passwordTxt.getText().isEmpty()
                || telTxt.getText().isEmpty() || correoTxt.getText().isEmpty()
                || dataDate.getDate() == null || cityCmb.getSelectedItem() == null
                || RolCmb.getSelectedItem() == null || IdentiCmb.getSelectedItem() == null) {
            return false;
        } else {
            return true;
        }
    }

    private void deleteEmpleado(java.awt.event.ActionEvent evt) {
        try {
            empleadoCrud.deleteById(Long.parseLong(idTxt.getText()));
            notificaTxt.setText("Se elimino el Cliente con ID: "
                    + idTxt.getText());
            limpiarReg();
            tabla.setRowCount(0);
            llenarTabla();
        } catch (Exception e) {
            notificaTxt.setText("Ocurrio un error al eliminar");
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> IdentiCmb;
    private javax.swing.JComboBox<String> RolCmb;
    public javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cityCmb;
    protected javax.swing.JPanel cityCrud;
    public javax.swing.JComboBox<String> cityRCmb;
    public javax.swing.JTextField correoTxt;
    private com.toedter.calendar.JDateChooser dataDate;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel dateTxt;
    public javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> depCmb;
    public javax.swing.JComboBox<String> depRCmb;
    public javax.swing.JTextField idTxt;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField lastTxt;
    public javax.swing.JTextField nameTxt;
    private javax.swing.JLabel notificaTxt;
    public javax.swing.JTextField passwordTxt;
    private javax.swing.ButtonGroup radioGrupAdmin;
    public javax.swing.JButton regButton;
    public javax.swing.JRadioButton regRb;
    public javax.swing.JRadioButton searchRb;
    public javax.swing.JTextField telTxt;
    public javax.swing.JButton updateButton;
    protected javax.swing.JPanel userCrud;
    public javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
