/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unad.poo.views;

import com.unad.poo.ProgramaJavaApplication;
import com.unad.poo.SpringContext;
import com.unad.poo.models.Admin;
import com.unad.poo.models.Empleado;
import com.unad.poo.repository.AdminRepository;
import com.unad.poo.repository.EmpleadoRepository;

/**
 *
 * @author FERNi
 */
public class AppLogin extends javax.swing.JFrame {

    EmpleadoRepository empleadoCrud;
    AdminRepository adminCrud;
    Empleado emp = new Empleado();

    /**
     * Creates new form AppLogin
     */
    public AppLogin() {
        initComponents();
        this.setSize(340, 270);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        String[] args = {};
        ProgramaJavaApplication.runSpringServer(args);

        empleadoCrud = SpringContext.getBean(EmpleadoRepository.class);
        adminCrud = SpringContext.getBean(AdminRepository.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginTxt = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        UserTxt = new javax.swing.JLabel();
        PassTxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        notificaTxt = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(340, 230));
        setSize(new java.awt.Dimension(340, 230));

        jPanel1.setMaximumSize(new java.awt.Dimension(340, 230));
        jPanel1.setMinimumSize(new java.awt.Dimension(340, 230));

        loginTxt.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        loginTxt.setText("Login");

        userTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        UserTxt.setFont(new java.awt.Font("Eras Demi ITC", 0, 15)); // NOI18N
        UserTxt.setText("Username");

        PassTxt.setFont(new java.awt.Font("Eras Demi ITC", 0, 15)); // NOI18N
        PassTxt.setText("Password");

        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        notificaTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 12)); // NOI18N
        notificaTxt.setText("\"\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PassTxt)
                                    .addComponent(UserTxt))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginTxt)
                                    .addComponent(userTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(passwordTxt))
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(notificaTxt)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(loginTxt)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserTxt)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PassTxt)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(notificaTxt)
                .addGap(14, 14, 14)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoguearUsuario();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void LoguearUsuario() {
        System.out.println(String.valueOf(passwordTxt.getPassword()));
        Admin adminLogin = adminCrud.findByUsernameAndContraseña(userTxt.getText(), String.valueOf(passwordTxt.getPassword()));
        if (adminLogin == null) {

            Empleado empleadoLogin = empleadoCrud.findByUsernameAndContraseña(userTxt.getText(), String.valueOf(passwordTxt.getPassword()));
            if (empleadoLogin == null) {
                StringBuffer respuesta = new StringBuffer();
                respuesta.append("Usuario no encontrado o password Invalida");
                notificaTxt.setText(respuesta.toString());
            } else {
                this.dispose();
                EmpleadoFrame empleadoPanel = new EmpleadoFrame();
                empleadoPanel.setVisible(true);
            }
        } else {
            this.dispose();
            AdminFrame adminPanel = new AdminFrame();
            adminPanel.setVisible(true);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PassTxt;
    private javax.swing.JLabel UserTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel notificaTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
