/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unad.poo.views;

import com.unad.poo.ProgramaJavaApplication;
import com.unad.poo.SpringContext;
import com.unad.poo.models.Ciudad;
import com.unad.poo.models.Clasificacion;
import com.unad.poo.models.Cliente;
import com.unad.poo.models.Departamento;
import com.unad.poo.models.Envios;
import com.unad.poo.repository.CiudadRepository;
import com.unad.poo.repository.ClasRepository;
import com.unad.poo.repository.ClienteRepository;
import com.unad.poo.repository.DepartamentoRepository;
import com.unad.poo.repository.EnvioRepository;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;
import java.util.Optional;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author FERNi
 */
public class EmpleadoFrame extends javax.swing.JFrame {

    CiudadRepository ciudadCrud;
    ClienteRepository clienteCrud;
    DepartamentoRepository depCrud;
    ClasRepository clasCrud;
    EnvioRepository envCrud;
    ArrayList<Departamento> datosDep = new ArrayList<>();
    ArrayList<Ciudad> datosCiudad = new ArrayList<>();
    ArrayList<Clasificacion> datosClas = new ArrayList<>();
    Cliente client = new Cliente();
    Envios env = new Envios();
    Ciudad ciudad = new Ciudad();
    Departamento dep = new Departamento();

    /**
     * Creates new form EmpleadoFrame
     */
    public EmpleadoFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(870, 420);
        this.setResizable(false);
        String[] args = {};
        ProgramaJavaApplication.runSpringServer(args);

        clienteCrud = SpringContext.getBean(ClienteRepository.class);
        ciudadCrud = SpringContext.getBean(CiudadRepository.class);
        depCrud = SpringContext.getBean(DepartamentoRepository.class);
        clasCrud = SpringContext.getBean(ClasRepository.class);
        envCrud = SpringContext.getBean(EnvioRepository.class);
        mostrarDepartamentos(depCmb);
        mostrarDepartamentos(depOCmb);
        mostrarDepartamentos(depDCmb);
        mostrarDepartamentos(depCCmb);
        mostrarClasificacion(clasCmb);
        bloquearCamposReg();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGrupo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        userCrud = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        regRb = new javax.swing.JRadioButton();
        searchRb = new javax.swing.JRadioButton();
        notificaTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        lastTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adressTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telTxt = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        dataDate = new com.toedter.calendar.JDateChooser();
        depCmb = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cityCmb = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        sendCrud = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cityOCmb = new javax.swing.JComboBox<>();
        cityDCmb = new javax.swing.JComboBox<>();
        idReTxt = new javax.swing.JTextField();
        idDesTxt = new javax.swing.JTextField();
        nameDesTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lastDesTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        adressDesTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        celDesTxt = new javax.swing.JTextField();
        clasCmb = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        envioButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        depOCmb = new javax.swing.JComboBox<>();
        depDCmb = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        notificaEnvTxt = new javax.swing.JLabel();
        cityCrud = new javax.swing.JPanel();
        depCCmb = new javax.swing.JComboBox<>();
        cityCCmb = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        numberUserTxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setText("Id Usuario");

        idTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        idTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idTxtFocusGained(evt);
            }
        });
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTxtKeyTyped(evt);
            }
        });

        radioGrupo.add(regRb);
        regRb.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        regRb.setText("Registrar");
        regRb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                regRbStateChanged(evt);
            }
        });
        regRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRbActionPerformed(evt);
            }
        });

        radioGrupo.add(searchRb);
        searchRb.setFont(new java.awt.Font("Eras Light ITC", 1, 16)); // NOI18N
        searchRb.setText("Consultar");
        searchRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRbActionPerformed(evt);
            }
        });

        notificaTxt.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        notificaTxt.setText("\"\"");

        jLabel3.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        nameTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        nameTxt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nameTxtInputMethodTextChanged(evt);
            }
        });
        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });
        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameTxtKeyTyped(evt);
            }
        });

        lastTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        lastTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastTxtKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel4.setText("Departamento:");

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel5.setText("Direccion:");

        adressTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        dateTxt.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        dateTxt.setText("Fecha de Nacimiento:");

        jLabel7.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");

        telTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        telTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telTxtKeyTyped(evt);
            }
        });

        regButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        regButton.setText("Registrar");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        updateButton.setText("Actualizar");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        deleteButton.setText("Eliminar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        depCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depCmbItemStateChanged(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel27.setText("Ciudad:");

        jLabel28.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel28.setText("Nombre:");

        cancelButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userCrudLayout = new javax.swing.GroupLayout(userCrud);
        userCrud.setLayout(userCrudLayout);
        userCrudLayout.setHorizontalGroup(
            userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCrudLayout.createSequentialGroup()
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(dateTxt)
                                    .addComponent(jLabel28))
                                .addGap(47, 47, 47)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCrudLayout.createSequentialGroup()
                                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(userCrudLayout.createSequentialGroup()
                                                .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(userCrudLayout.createSequentialGroup()
                                                .addComponent(dataDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(26, 26, 26)))
                                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(userCrudLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lastTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(userCrudLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(adressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(userCrudLayout.createSequentialGroup()
                                        .addComponent(depCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(regButton)
                                .addGap(47, 47, 47)
                                .addComponent(updateButton)
                                .addGap(42, 42, 42)
                                .addComponent(deleteButton)))
                        .addGap(36, 36, 36)
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchRb)
                            .addComponent(regRb))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userCrudLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(377, 377, 377))
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel27)
                                .addGap(47, 47, 47)
                                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notificaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userCrudLayout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        userCrudLayout.setVerticalGroup(
            userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lastTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(adressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateTxt))
                            .addComponent(dataDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(telTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(depCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(userCrudLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(regRb)
                        .addGap(18, 18, 18)
                        .addComponent(searchRb)))
                .addGap(18, 18, 18)
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cityCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", userCrud);

        jLabel6.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel6.setText("Ciudad:");

        jLabel8.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        jLabel8.setText("Ciudad:");

        jLabel9.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel9.setText("Cedula:");

        jLabel10.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel10.setText("Cedula:");

        jLabel11.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel11.setText("Nombre:");

        jLabel12.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel12.setText("Clasificacion:");

        cityOCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        cityOCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityOCmbActionPerformed(evt);
            }
        });

        cityDCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        idReTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        idReTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idReTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idReTxtFocusLost(evt);
            }
        });
        idReTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReTxtActionPerformed(evt);
            }
        });
        idReTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idReTxtKeyTyped(evt);
            }
        });

        idDesTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        idDesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idDesTxtKeyTyped(evt);
            }
        });

        nameDesTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        nameDesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameDesTxtKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel13.setText("Apellido:");

        lastDesTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        lastDesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastDesTxtKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel14.setText("Direccion:");

        adressDesTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        adressDesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adressDesTxtKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel15.setText("Celular:");

        celDesTxt.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        celDesTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celDesTxtKeyTyped(evt);
            }
        });

        clasCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel16.setText("Remitente");

        jLabel17.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel17.setText("Destinatario");

        envioButton.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        envioButton.setText("Ingresar Envio");
        envioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel18.setText("Departamento:");

        jLabel19.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel19.setText("Departamento:");

        depOCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        depOCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depOCmbItemStateChanged(evt);
            }
        });

        depDCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        depDCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depDCmbItemStateChanged(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N
        jLabel20.setText("Origen");

        jLabel21.setFont(new java.awt.Font("Eras Demi ITC", 0, 20)); // NOI18N
        jLabel21.setText("Destino");

        notificaEnvTxt.setFont(new java.awt.Font("Eras Demi ITC", 0, 14)); // NOI18N
        notificaEnvTxt.setText("\"\"");

        javax.swing.GroupLayout sendCrudLayout = new javax.swing.GroupLayout(sendCrud);
        sendCrud.setLayout(sendCrudLayout);
        sendCrudLayout.setHorizontalGroup(
            sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendCrudLayout.createSequentialGroup()
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sendCrudLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendCrudLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sendCrudLayout.createSequentialGroup()
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cityOCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depOCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel16))
                        .addGap(100, 100, 100)
                        .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(sendCrudLayout.createSequentialGroup()
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cityDCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depDCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(sendCrudLayout.createSequentialGroup()
                        .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sendCrudLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(envioButton)
                                    .addGroup(sendCrudLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(idReTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(sendCrudLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(sendCrudLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(notificaEnvTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(100, 100, 100)
                        .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(sendCrudLayout.createSequentialGroup()
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adressDesTxt)
                                    .addComponent(lastDesTxt)
                                    .addComponent(celDesTxt)))
                            .addGroup(sendCrudLayout.createSequentialGroup()
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(207, 207, 207))
        );
        sendCrudLayout.setVerticalGroup(
            sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendCrudLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(depOCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depDCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(cityOCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityDCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(idReTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nameDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notificaEnvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lastDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clasCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(adressDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sendCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(celDesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(envioButton))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Envios", sendCrud);

        depCCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N
        depCCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depCCmbItemStateChanged(evt);
            }
        });

        cityCCmb.setFont(new java.awt.Font("Eras Light ITC", 0, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel22.setText("Departamento:");

        jLabel23.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel23.setText("Ciudad:");

        jLabel24.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        jLabel24.setText("Usuarios por Ciudad");

        jLabel25.setFont(new java.awt.Font("Eras Demi ITC", 1, 18)); // NOI18N
        jLabel25.setText("NUMERO DE USUARIOS:");

        numberUserTxt.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        numberUserTxt.setText("jLabel26");

        jButton1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cityCrudLayout = new javax.swing.GroupLayout(cityCrud);
        cityCrud.setLayout(cityCrudLayout);
        cityCrudLayout.setHorizontalGroup(
            cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityCrudLayout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cityCrudLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(27, 27, 27)
                        .addComponent(numberUserTxt)
                        .addGap(23, 23, 23))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cityCrudLayout.createSequentialGroup()
                        .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(38, 38, 38)
                        .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depCCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityCCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cityCrudLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel24)
                        .addGap(74, 74, 74)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        cityCrudLayout.setVerticalGroup(
            cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cityCrudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(30, 30, 30)
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depCCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(27, 27, 27)
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityCCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addGroup(cityCrudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberUserTxt)
                    .addComponent(jLabel25))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ciudad", cityCrud);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        registrarOActualizarCliente();
        // TODO add your handling code here:
    }//GEN-LAST:event_regButtonActionPerformed

    public Ciudad obtenerIdCiudad(String cityName) {
        Ciudad ciudadName = ciudadCrud.findByNombre(cityName);
        return ciudadName;
    }

    public Clasificacion obtenerIdClasificacion(String clasName) {
        Clasificacion ClasName = clasCrud.findByNombre(clasName);
        return ClasName;
    }

    private void registrarOActualizarCliente() {

        client = setterCliente(cityCmb);

        if (validarCamposNullos() == false) {
            JOptionPane.showMessageDialog(this, "No se aceptan campos Nullos",
                    "Cliente no guardado", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                clienteCrud.save(client);
                notificaTxt.setText("Usuario guardado exitosamente");
                limpiarReg();
                idTxt.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Campos sin Llenar o "
                        + "llenados incorrectamente", "Cliente no guardado",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private boolean validarCamposNullos() {
        if (nameTxt.getText().isEmpty() || lastTxt.getText().isEmpty()
                || adressTxt.getText().isEmpty() || telTxt.getText().isEmpty()
                || dataDate.getDate() == null || cityCmb.getSelectedItem() == null) {
            return false;
        } else {
            return true;
        }
    }

    private boolean validarCamposNullosEnv() {
        if (nameDesTxt.getText().isEmpty() || lastDesTxt.getText().isEmpty()
                || adressDesTxt.getText().isEmpty() || celDesTxt.getText().isEmpty()
                || cityDCmb.getSelectedItem() == null || cityOCmb.getSelectedItem() == null
                || idDesTxt.getText().isEmpty() || idReTxt.getText().isEmpty()
                || clasCmb.getSelectedItem() == null) {
            return false;
        } else {
            return true;
        }
    }

    //Programa los setter a la clase Cliente, de este modo con .save se guardan los datos en la base
    //datos. Sirve tanto para crear como para actualizar.
    private Cliente setterCliente(JComboBox cityId) {
        client.setId(Long.parseLong(idTxt.getText()));
        client.setNombre(nameTxt.getText());
        client.setApellido(lastTxt.getText());
        client.setFecha_n(dataDate.getDate());
        client.setCiudad(obtenerIdCiudad(cityId.getSelectedItem().toString()));
        client.setDireccionCliente(adressTxt.getText());
        client.setCelular(telTxt.getText());

        return client;
    }

    private Envios setterEnvio(JComboBox cityRem, JComboBox cityDes) {
        try {
            Optional<Cliente> buscaCliente = clienteCrud.findById(Long.parseLong(idReTxt.getText()));
            env.setCliente(buscaCliente.get());
            env.setIdDest(Long.parseLong(idDesTxt.getText()));
            env.setNombreDest(nameDesTxt.getText());
            env.setApellidoDest(lastDesTxt.getText());
            env.setCelularDest(celDesTxt.getText());
            env.setDireccionDest(adressDesTxt.getText());
            env.setIdClasificacio(obtenerIdClasificacion(clasCmb.getSelectedItem().toString()));
            env.setCiudadOrigen(obtenerIdCiudad(cityRem.getSelectedItem().toString()).getIdCiudad());
            env.setCiudadDestino(obtenerIdCiudad(cityDes.getSelectedItem().toString()).getIdCiudad());
            env.setFecha(Calendar.getInstance().getTime());
        } catch (Exception e) {
 //ejecute una de las excepciones al tratar de hacer crud.
        }

        return env;
    }
    
    private void registrarEnvio() {

        env = setterEnvio(cityOCmb, cityDCmb);

        if (validarCamposNullosEnv() == false) {
            JOptionPane.showMessageDialog(this, "No se aceptan campos Nullos",
                    "Envio no Guardado", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                envCrud.save(env);
                notificaEnvTxt.setText("Envio registrado exitosamente");
                limpiarRegEnv();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Campos sin Llenar o "
                        + "llenados incorrectamente", "Envio no registrado",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    /*
        Queda por Programar...
            Envios env1 = envCrud.findTopByClienteAndIdDestOrderByFechaDesc(env.getCliente(), env.getIdDest());
            System.out.println(env1);
    
            Con este codigo puedo obtener el ID del registro de Envios que acaba de acerse.
            el objetivo es crear una especie de desprendible parecido al que tiene ServiEntrega
            para entregarle al usuario y marcar las cajas o envios.
    
            Por el momento no encontre informacion de como hacer un desprendible decente. por lo cual sigo en la busqueda
            solo vi que con JasperReport como que se puede hacer algo parecido.
    
            Idea...

    */
    
    private void imprimirTiquetEnv(Envios env){
        
    }
    
    

    private void bloquearCamposReg() {
        nameTxt.setEnabled(false);
        lastTxt.setEnabled(false);
        dataDate.setEnabled(false);
        depCmb.setEnabled(false);
        cityCmb.setEnabled(false);
        adressTxt.setEnabled(false);
        telTxt.setEnabled(false);
        regButton.setEnabled(false);
        updateButton.setEnabled(false);
        deleteButton.setEnabled(false);
        cancelButton.setEnabled(false);
    }

    private void habilitarCamposReg() {
        nameTxt.setEnabled(true);
        lastTxt.setEnabled(true);
        dataDate.setEnabled(true);
        depCmb.setEnabled(true);
        cityCmb.setEnabled(true);
        adressTxt.setEnabled(true);
        telTxt.setEnabled(true);
    }

    private void funcionRadioButtons() {
        //isPresent retorna null
        Optional<Cliente> buscaCliente = clienteCrud.findById(Long.parseLong(idTxt.getText()));
        if (buscaCliente.isPresent()) {
            if (regRb.isSelected()) {
                notificaTxt.setText("El Cliente con id: " + idTxt.getText() + "\n ya existe");
                radioGrupo.clearSelection();
            }

            if (searchRb.isSelected()) {
                regRb.setEnabled(false);
                habilitarCamposReg();
                idTxt.setEnabled(false);
                nameTxt.setText(buscaCliente.get().getNombre());
                lastTxt.setText(buscaCliente.get().getApellido());
                dataDate.setDate(buscaCliente.get().getFecha_n());
                depCmb.setSelectedItem(buscaCliente.get().getCiudad().getIdDepartamento().getNombre());
                cityCmb.setSelectedItem(buscaCliente.get().getCiudad().getNombre());
                adressTxt.setText(buscaCliente.get().getDireccionCliente());
                telTxt.setText(buscaCliente.get().getCelular());
                updateButton.setEnabled(true);
                deleteButton.setEnabled(true);
                cancelButton.setEnabled(true);
            }
        } else {
            if (regRb.isSelected()) {
                habilitarCamposReg();
                idTxt.setEnabled(false);
                regButton.setEnabled(true);
                searchRb.setEnabled(false);
                notificaTxt.setText("id Disponible");
                cancelButton.setEnabled(true);
            }
            if (searchRb.isSelected()) {
                notificaTxt.setText("El Cliente con id " + idTxt.getText() + "\n no existe");
                radioGrupo.clearSelection();
            }
        }
    }

    private void limpiarReg() {
        nameTxt.setText("");
        lastTxt.setText("");
        dataDate.setCalendar(null);
        depCmb.setSelectedIndex(1);
        adressTxt.setText("");
        telTxt.setText("");
        radioGrupo.clearSelection();
        regRb.setEnabled(true);
        searchRb.setEnabled(true);
        notificaTxt.setText("");
        idTxt.setEnabled(true);
        bloquearCamposReg();
    }

    private void limpiarRegEnv() {
        nameDesTxt.setText("");
        lastDesTxt.setText("");
        depOCmb.setSelectedIndex(1);
        depDCmb.setSelectedIndex(1);
        adressDesTxt.setText("");
        celDesTxt.setText("");
        idReTxt.setText("");
        idDesTxt.setText("");
        clasCmb.setSelectedIndex(1);
    }

    private void depCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depCmbItemStateChanged
        // TODO add your handling code here:
        changeStateDep(evt, depCmb, cityCmb);
    }//GEN-LAST:event_depCmbItemStateChanged

    private void cityOCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityOCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityOCmbActionPerformed

    private void depOCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depOCmbItemStateChanged
        changeStateDep(evt, depOCmb, cityOCmb);
        // TODO add your handling code here:
    }//GEN-LAST:event_depOCmbItemStateChanged

    private void depDCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depDCmbItemStateChanged
        changeStateDep(evt, depDCmb, cityDCmb);
        // TODO add your handling code here:
    }//GEN-LAST:event_depDCmbItemStateChanged

    private void depCCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depCCmbItemStateChanged
        changeStateDep(evt, depCCmb, cityCCmb);
        // TODO add your handling code here:
    }//GEN-LAST:event_depCCmbItemStateChanged

    private void nameTxtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nameTxtInputMethodTextChanged
// TODO add your handling code here:
    }//GEN-LAST:event_nameTxtInputMethodTextChanged

    private void idTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyTyped
        verificaLetra(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtKeyTyped

    private void nameTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyTyped
        verificaNumero(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtKeyTyped

    private void lastTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastTxtKeyTyped
        verificaNumero(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_lastTxtKeyTyped

    private void telTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telTxtKeyTyped
        verificaLetra(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_telTxtKeyTyped

    private void regRbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_regRbStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_regRbStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        limpiarReg();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void regRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRbActionPerformed
        funcionRadioButtons();
        // TODO add your handling code here:
    }//GEN-LAST:event_regRbActionPerformed

    private void searchRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRbActionPerformed
        funcionRadioButtons();
        // TODO add your handling code here:
    }//GEN-LAST:event_searchRbActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        registrarOActualizarCliente();

        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            clienteCrud.deleteById(Long.parseLong(idTxt.getText()));
            notificaTxt.setText("Se elimino el Cliente con ID: "
                    + idTxt.getText());
            limpiarReg();
        } catch (Exception e) {
            notificaTxt.setText("Ocurrio un error al eliminar");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void idTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idTxtFocusGained
        notificaTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtFocusGained

    private void idReTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idReTxtActionPerformed

    private void envioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioButtonActionPerformed
        registrarEnvio();

        // TODO add your handling code here:
    }//GEN-LAST:event_envioButtonActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void idReTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idReTxtKeyTyped
        verificaLetra(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_idReTxtKeyTyped

    private void idDesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idDesTxtKeyTyped
        verificaLetra(evt);// TODO add your handling code here:
    }//GEN-LAST:event_idDesTxtKeyTyped

    private void nameDesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameDesTxtKeyTyped
        verificaNumero(evt);// TODO add your handling code here:
    }//GEN-LAST:event_nameDesTxtKeyTyped

    private void lastDesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastDesTxtKeyTyped
        verificaNumero(evt);
// TODO add your handling code here:
    }//GEN-LAST:event_lastDesTxtKeyTyped

    private void adressDesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adressDesTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_adressDesTxtKeyTyped

    private void celDesTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celDesTxtKeyTyped
        verificaLetra(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_celDesTxtKeyTyped

    private void idReTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idReTxtFocusLost
        if (idReTxt.getText().isEmpty()) {
        } else {
            Optional<Cliente> buscaCliente = clienteCrud.findById(Long.parseLong(idReTxt.getText()));
            if (buscaCliente.isPresent()) {

            } else {
                int respuestas = JOptionPane.showConfirmDialog(null, "El Cliente con ID: "
                        + "" + idReTxt.getText()
                        + " no exite. ¿Desea Registrar este Cliente?.", "Cliente"
                        + " no Registrado", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (respuestas == 0) {
                    jTabbedPane1.setSelectedIndex(0);
                    idTxt.setText(idReTxt.getText());
                    idReTxt.setText(null);
                } else {
                    idReTxt.setText(null);
                    idReTxt.requestFocus();
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_idReTxtFocusLost

    private void idReTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idReTxtFocusGained
        notificaEnvTxt.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_idReTxtFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usersByCity();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usersByCity(){
        try{
            Long usuarios = clienteCrud.countByCiudad(obtenerIdCiudad(cityCCmb.getSelectedItem().toString()));
            numberUserTxt.setText(usuarios.toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No existen usuarios registrados en la ciudad seleccionada", "No se encontraron Usuarios", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    
    private void verificaLetra(java.awt.event.KeyEvent evt) {
        if (Character.isLetter(evt.getKeyChar())) {
            evt.consume();
        }
    }

    private void verificaNumero(java.awt.event.KeyEvent evt) {
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }

    /**
     * @param departamentoCmb
     * @param args the command line arguments
     */
    public void mostrarDepartamentos(JComboBox departamentoCmb) {

        datosDep = (ArrayList<Departamento>) depCrud.findAll();
        Iterator<Departamento> miIterador = datosDep.iterator();

        while (miIterador.hasNext()) {
            departamentoCmb.addItem(miIterador.next().getNombre());
        }

    }

    public void mostrarCiudad(JComboBox depCmbx, JComboBox ciudadCmbx) {
        String itemSelect = (String) depCmbx.getSelectedItem();
        datosCiudad = (ArrayList<Ciudad>) ciudadCrud.findAll();

        for (int i = 0; i < datosCiudad.size(); i++) {
            if (datosCiudad.get(i).getIdDepartamento().getNombre().equals(itemSelect)) {
                ciudadCmbx.addItem(datosCiudad.get(i).getNombre());
            }
        }

    }

    private void mostrarClasificacion(JComboBox clasificacionCmb) {
        datosClas = (ArrayList<Clasificacion>) clasCrud.findAll();
        Iterator<Clasificacion> clasIterator = datosClas.iterator();
        while (clasIterator.hasNext()) {
            clasificacionCmb.addItem(clasIterator.next().getNombre());
        }
    }
    
    public void changeStateDep(java.awt.event.ItemEvent evt, JComboBox departamentoCmb, JComboBox ciudadCmb){
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ciudadCmb.removeAllItems();
            mostrarCiudad(departamentoCmb, ciudadCmb);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField adressDesTxt;
    public javax.swing.JTextField adressTxt;
    public javax.swing.JButton cancelButton;
    public javax.swing.JTextField celDesTxt;
    public javax.swing.JComboBox<String> cityCCmb;
    public javax.swing.JComboBox<String> cityCmb;
    protected javax.swing.JPanel cityCrud;
    public javax.swing.JComboBox<String> cityDCmb;
    public javax.swing.JComboBox<String> cityOCmb;
    public javax.swing.JComboBox<String> clasCmb;
    private com.toedter.calendar.JDateChooser dataDate;
    private javax.swing.JLabel dateTxt;
    public javax.swing.JButton deleteButton;
    public javax.swing.JComboBox<String> depCCmb;
    public javax.swing.JComboBox<String> depCmb;
    public javax.swing.JComboBox<String> depDCmb;
    public javax.swing.JComboBox<String> depOCmb;
    public javax.swing.JButton envioButton;
    public javax.swing.JTextField idDesTxt;
    public javax.swing.JTextField idReTxt;
    public javax.swing.JTextField idTxt;
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    protected javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField lastDesTxt;
    public javax.swing.JTextField lastTxt;
    public javax.swing.JTextField nameDesTxt;
    public javax.swing.JTextField nameTxt;
    private javax.swing.JLabel notificaEnvTxt;
    private javax.swing.JLabel notificaTxt;
    public javax.swing.JLabel numberUserTxt;
    private javax.swing.ButtonGroup radioGrupo;
    public javax.swing.JButton regButton;
    public javax.swing.JRadioButton regRb;
    public javax.swing.JRadioButton searchRb;
    protected javax.swing.JPanel sendCrud;
    public javax.swing.JTextField telTxt;
    public javax.swing.JButton updateButton;
    protected javax.swing.JPanel userCrud;
    // End of variables declaration//GEN-END:variables

}
